# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myDjangos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'medicines',
            },
        ),
        migrations.CreateModel(
            name='MedicineDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_document_name', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MedicalDocument',
        ),
        migrations.AddField(
            model_name='medicine',
            name='medicine_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myDjangos.MedicineDocument'),
        ),
    ]
